wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704043034.177639
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.12.1
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
