name: mlflow-f5e4621dc2c95d37173abc9be60026b236dbade5
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.13.1=pyhd8ed1ab_0
  - aws-c-auth=0.7.8=h251af53_3
  - aws-c-cal=0.6.9=hb1772db_2
  - aws-c-common=0.9.10=h93a5062_0
  - aws-c-compression=0.2.17=hb1772db_7
  - aws-c-event-stream=0.3.2=hb5e90b3_8
  - aws-c-http=0.7.15=hd747585_0
  - aws-c-io=0.13.36=h1112932_3
  - aws-c-mqtt=0.10.0=h3e71869_1
  - aws-c-s3=0.4.6=ha7f36e9_0
  - aws-c-sdkutils=0.1.13=hb1772db_0
  - aws-checksums=0.1.17=hb1772db_6
  - aws-crt-cpp=0.25.0=h0fe04c1_4
  - aws-sdk-cpp=1.11.210=h87406ae_5
  - bcrypt=4.1.2=py311h94f323b_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.24.0=h93a5062_0
  - ca-certificates=2023.11.17=hf0a4a13_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hd03642b_0
  - cryptography=41.0.7=py311h08c85a6_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - flask=3.0.0=pyhd8ed1ab_0
  - fonttools=4.47.0=py311h05b510d_0
  - freetype=2.12.1=hadb7bae_2
  - gflags=2.2.2=hc88da5d_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - greenlet=3.0.3=py311h92babd0_0
  - gunicorn=21.2.0=py311h267d04e_1
  - icu=73.2=hc8870d7_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libarrow=14.0.2=hfcbd24e_0_cpu
  - libarrow-acero=14.0.2=h13dd4ca_0_cpu
  - libarrow-dataset=14.0.2=h13dd4ca_0_cpu
  - libarrow-flight=14.0.2=ha94d253_0_cpu
  - libarrow-flight-sql=14.0.2=h39a9b85_0_cpu
  - libarrow-gandiva=14.0.2=hf757142_0_cpu
  - libarrow-substrait=14.0.2=h7fd9903_0_cpu
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.5.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=hbcf6334_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm15=15.0.7=h2621b3d_4
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libparquet=14.0.2=hf6ce1d5_0_cpu
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.24.4=hc9861d8_0
  - libre2-11=2023.06.02=h1753957_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=ha8a6c65_2
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.3=h0d0cfa8_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.6=hcd81f8e_0
  - lz4-c=1.9.4=hb7217d7_0
  - mako=1.3.0=pyhd8ed1ab_0
  - markdown=3.5.1=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311heffc1b2_1
  - matplotlib=3.8.2=py311ha1ab1f8_0
  - matplotlib-base=3.8.2=py311hfdba5f6_0
  - mlflow=2.9.2=py311h10ef9e2_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h463b476_2
  - numpy=1.26.2=py311h6d074dd_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.2.0=h0d3ecfb_1
  - orc=1.9.2=h7c018df_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py311h6e08293_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - pillow=10.1.0=py311hb9c5795_0
  - pip=23.3.2=pyhd8ed1ab_0
  - plotly=5.18.0=pyhd8ed1ab_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - protobuf=4.24.4=py311h4d1eceb_0
  - pthread-stubs=0.4=h27ca646_1001
  - pyarrow=14.0.2=py311hd7bc329_0_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py311heffc1b2_3
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.7=hdf0ec26_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py311heffc1b2_1
  - querystring_parser=1.2.4=py_0
  - re2=2023.06.02=h6135d0a_0
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py311ha25ca4d_2
  - scipy=1.11.4=py311h2b215a9_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sqlalchemy=2.0.23=py311h05b510d_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.3.3=py311heffc1b2_1
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - psutil==5.9.7
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - wandb==0.16.1
prefix: /Users/AahanAgrawal/miniconda3/envs/mlflow-f5e4621dc2c95d37173abc9be60026b236dbade5
